import { Inter } from 'next/font/google';
import './globals.css';

export const metadata = {
  title: 'ClassAid App',
  description: 'Generated by create next app',
  author: 'Mariela González',
  icons: {
    icon: [
      { url: '/public/icons/classaid_favicon.ico' },
      { url: '/icons/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/icons/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
    ],
    apple: '/icons/apple-touch-icon.png',
  },
};

const inter = Inter({ variable: '--font-inter', subsets: ['latin'], display: 'swap' });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        />
        {/* <link rel="shortcut icon" href="/icons/favicon.ico" /> */}
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
      </head>
      <body>{children}</body>
    </html>
  );
}
