import "./globals.css";

export const metadata = {
  title: "ClassAid App",
  description: "Generated by create next app",
  author: "Mariela González",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
