//'use client';

import { Inter } from 'next/font/google';
import './(frontend)/globals.css';
import { Toaster } from 'react-hot-toast';
import Providers from '@/context/Providers';
import { PROTECTED_ROUTES } from '@/utils/constants';
//import { usePathname } from 'next/navigation';

export const metadata = {
  title: 'ClassAid',
  description: 'Generated by create next app',
  author: [
    { name: 'Mariela González', url: 'https://github.com/mmgonnar' },
    { name: 'Horacio Gutierrez', url: 'https://github.com/HoracioGutierrez' },
    { name: 'Sarah Alfonsin', url: 'https://www.linkedin.com/in/sarahalfonsin/' },
  ],
  icons: {
    icon: [
      { url: '/icons/favicon.ico' },
      { url: '/icons/favicon.ico', sizes: '32x32', type: 'image/png' },
      { url: '/icons/favicon.ico', sizes: '16x16', type: 'image/png' },
    ],
    apple: '/icons/apple-touch-icon.png',
  },
};

//const inter = Inter({ variable: '--font-inter', subsets: ['latin'], display: 'swap' });

export default function RootLayout({ children }) {
  //const pathname = usePathname();

  //const isProtectedRoute = PROTECTED_ROUTES.some((route) => pathname?.startsWith(route));

  return (
    <html
      lang="en"
      // className={inter.variable}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        />
        {/* <link rel="shortcut icon" href="/icons/favicon.ico" /> */}
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
      </head>
      <body
      // className={isProtectedRoute ? "overflow-hidden" : "overflow-auto"}
      >
        <Providers>
          {children} <Toaster position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
